Switch to the new jeweler rake tasks
Avoid recursive dependency:

Fetching: workflow-0.8.4.gem (100%)
ERROR:  Error installing workflow:
    workflow requires workflow (>= 0)